version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    ports:
      - '3309:3306'
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_USER=bot
      - MARIADB_PASSWORD=example
      - MARIADB_ROOT_PASSWORD=exampleroot
      - MARIADB_DATABASE=bdoguild
